### ISSUE TITLE
SeqPrep installation problem

### ISSUE THREAD

**Issue by pcastro88** [jstjohn/SeqPrep#24]
Hi
I am trying to install SeqPrep but after make command this error appears and I am not figuring it out
Do you have any suggestions to overcome it? (I am using Linux mint maya 64bit)

cc  SeqPrep.o utils.o stdaln.o -lz -lm -o SeqPrep
SeqPrep.o: In function `main':
/home/pedro/Soft/SeqPrep-master/SeqPrep.c:350: undefined reference to `update_spinner'
collect2: ld returned 1 exit status
make: *** [SeqPrep] Error 1

kind regards,
Pedro Castro

**Comment by jstjohn** [comment]
Interesting. Which version of a c compiler are you using? If you have a specific version of gcc you use, you can compile with `make CC=gcc-4.X` for example.

**Comment by pcastro88** [comment]
thanks for you reply
im using gcc 4:4.6.3

I tried you suggestion but didn't make it (command not found)

**Comment by sariya** [comment]
Hi John,

I'm the having same issue. 

My cluster details:
`gcc version 4.7.0 (GCC)` 
`Thread model: posix`
This https://github.com/jstjohn/SeqPrep/issues/22 mentions to remove `extern` 
This however, worked, and I'm having binary of the tool.

Could you please confirm if this would have any downstream impact while joining paired end reads?

Thanks.
--Sariya

**Comment by jstjohn** [comment]
Yea it will probably be a fairly easy fix if someone gets time. It will likely be to just remove extern and inline modifiers from function definitions in both .h and .c files. Newer compilers seem to have problems with this. I doubt it will be much of a change in performance, and it will be closer to standard C syntax that is likely more portable.

**Comment by sariya** [comment]
@jstjohn Thanks for confirming.
I'm using this tool with QIIME joining paired ends. 

Merci,
--Sariya

**Comment by samdemorest** [comment]
#33 Specifying the C standard in the makefile resolves this build issue.
