### ISSUE TITLE
what's the different between -1 -2 options and -3 -4 options?

### ISSUE THREAD

**Issue by sheitandard** [jstjohn/SeqPrep#25]
Hi,

I am probably missing something obvious. If I get it right -1 and -2 contain not merged reads R1 and R2, and -3 -4 contain discarded reads. 
Isn't it the same thing?

**Comment by jstjohn** [comment]
Discarded reads are too short, or fail qc for some other reason after
adapter trimming.

**Comment by sheitandard** [comment]
thanks for the quick reply

are the reads discarded before the merging or after ?

**Comment by jstjohn** [comment]
After. They are put into the files unmerged though.
Also merging is optional. You can just use this to trim adapters from
paired reads.

**Comment by sheitandard** [comment]
Actually, only the merging interests me
are the files unmerged option -1 and -2?
It looks like the discarded reads are only in the discarded files
anyway, i can find all my unmerged reads by concatenating -1 with -3 and -2 with -4

thanks for all
